# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: npm install rescript && npx rescript init . # runs during prebuild
    # command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
vscode:
  extensions:
    # need to link to .vsix as rescript-vscode extension is not in https://open-vsx.org/
    - https://github.com/rescript-lang/rescript-vscode/releases/download/1.8.2/rescript-vscode-1.8.2.vsix
